### ISSUE TITLE
Write Python client automatically

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/MetagenomicsClient#1]
Use GitHub Actions to automatically write Python client code back to a subdirectory in this repo. See demo code in README.md, it is a one-liner.

**Comment by lwaldron** [comment]
(I mean creating the Python client is a one-liner, not the GHA :) )

**Comment by jwokaty** [comment]
Do we periodically update it after the initial creation? How often should we update or should something trigger the update?

**Comment by lwaldron** [comment]
I think my thinking here was that this would just be a convenience to make sure that the Python client keeps up to date, but I'm not sure if it's really even needed. If we do this, either a periodic or manual trigger would probably be fine. @sdgamboa what do you think, first about whether it's needed, and second if so, how to trigger?

**Comment by sdgamboa** [comment]
I think the API will keep changing, so I think it's needed. Maybe if there is a way to update the client only if the API changes?

**Comment by seandavi** [comment]
Interrepo GitHub actions are possible using repository dispatch. However, it is probably desirable to have a manual step included until some testing is in place.

**Comment by jwokaty** [comment]
Thanks for the feedback, everyone. I'll write the action to make a PR for each update that we need to manually merge. The PR will only be created when there's change, so I can schedule a cron to run the action weekly (and add a button to run it manually). If a repository dispatch is set up on the other repo, I can add it as a trigger later.
